# fly.toml app configuration file generated for aspiring-dev on 2024-01-30T16:32:14-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aspiring-dev"
primary_region = "iad"

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = false
auto_start_machines = false
min_machines_running = 1
processes = ["app"]

[mounts]
source = "aspiringdev"
destination = "/app/sqlite"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory_mb = 1024

[env]
S3_BUCKET = "aspiringdev-litestream"
S3_ENDPOINT = "https://80dda379301ddc81dae5cb6b31d27e99.r2.cloudflarestorage.com"
LITESTREAM_S3_URL = "https://80dda379301ddc81dae5cb6b31d27e99.r2.cloudflarestorage.com/aspiringdev-litestream/sqlite.db"
LOG_LEVEL = "debug"
MY_URL = "https://aspiring.dev"
AWS_DEFAULT_REGION = "us-east-1"
